# docker-compose.yml

version: '3.8'

services:
  server:
    build: .
    container_name: api_server
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - 8008:8000
    depends_on:
      - db
    networks:
      - practice

  db:
    image: postgres:14-alpine
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - practice
    
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
        - 16543:80
    networks:
      - practice
    # volumes:
    #     - ./servers.json:/pgadmin4/servers.json

volumes:
  postgres_data:

# add networks
networks:
  practice: