# docker-compose.yml

version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: fastapi
    command: uvicorn app.api.server:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./server/:/server/
    env_file:
      - ./server/.env
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./server/.env
    ports:
      - 5432:5432
 
volumes:
    postgres_data: