# docker-compose.yml

version: '3.8'

services:
  server:
    build: .
    container_name: api_server
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - 8000:8000