"""removed slug from table

Revision ID: 018e73821f19
Revises: 866dab5890b5
Create Date: 2024-01-19 21:24:38.113783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '018e73821f19'
down_revision: Union[str, None] = '866dab5890b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('plant_slug_key', 'plant', type_='unique')
    op.drop_column('plant', 'slug')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant', sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('plant_slug_key', 'plant', ['slug'])
    # ### end Alembic commands ###
